version: '3.9'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  db:
    image: postgres
    container_name: db_container
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/cache:/data

  django:
    container_name: django_container
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
        - DJANGO_DEBUG=$DJANGO_DEBUG
        - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS

    volumes:
      - .:/code
      - ..:/workspace:cached
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: sleep infinity
